name: buttermap
channels:
  - conda-forge
  - bioconda
dependencies:
  - bcftools=1.18
  - freebayes=1.3.7
  - minimap2=2.26
  - pip=23.3.1
  - pytest=7.4.3
  - ruffus=2.8.4
  - sambamba=1.0
  - samtools=1.18
  - bwa=0.7
  - pip:
    - dist/buttermap-0.0.1-py3-none-any.whl