name: buttermap
channels:
  - anaconda
  - conda-forge
  - bioconda
dependencies:
  - python=3.11.5
  - ruffus=2.8.4
  - joblib=1.2.0
  - minimap2=2.25
  - samtools=1.17
  - bcftools=1.17
  - sambamba=1.0.*
  - freebayes=1.3.6
  - pip
  - pip:
    - dist/buttermap-0.0.1-py3-none-any.whl